### ISSUE TITLE
Change date format to yyyy-mm-dd in all datasets

### ISSUE THREAD

**Issue by allopole** [CEIDatUGA/COVID-19-DATA#45]
I'd recommend changing the date format for time series CSVs to ISO standard yyyy-mm-dd.  

For example, in https://github.com/CEIDatUGA/COVID-19-DATA/blob/master/US/US_wikipedia_cases_fatalities/read_UScases_wikipedia.R 

This would work for now, until next year...

as.Date(paste(cases$Date, "2020"), "%b %d %Y")

Note, for many of our models, we start time on December 1, 2019. We also anticipate  data in 2021 at least.

**Comment by allopole** [comment]
Would require notifying data users of the change.

**Comment by mvevans89** [comment]
Yeah we have this as our recommendation in the instructions for adding datasets to this repo and asked people to do this when initially moving things into this repo, but whether individuals follow it is up to them. I don't mind going through to change some of the code if the owners have already okayed me changing things up, but otherwise what I can do is just remind people again to please change this.

**Comment by lsalvador** [comment]
I have changed US wiki files date to ISO standard. Sorry for not doing it earlier.
